import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <head>
        <link rel="preload" href="/Fonts/Foun/OpenType-TT/Foun.ttf" as="font" type="font/ttf" crossOrigin="anonymous" />
        <link rel="preload" href="/Fonts/Wenssep/Wenssep.ttf" as="font" type="font/ttf" crossOrigin="anonymous" />
        <link rel="preload" href="/Fonts/Maheni/Maheni-Regular.ttf" as="font" type="font/ttf" crossOrigin="anonymous" />
        <link rel="preload" href="/Fonts/otilito-sans-font-family-2026-04-07-06-24-36-utc/OTF/TBJOtilito-Regular.otf" as="font" type="font/otf" crossOrigin="anonymous" />
        <link rel="preload" href="/Fonts/qogee-font-2026-04-07-06-00-04-utc/Qogee.otf" as="font" type="font/otf" crossOrigin="anonymous" />
        <link rel="preload" href="/Fonts/Matina/Font/Matina-Regular.woff2" as="font" type="font/woff2" crossOrigin="anonymous" />
        <link rel="preload" href="/Fonts/News%20Deck/FONT/QUICK-ZIP.woff" as="font" type="font/woff" crossOrigin="anonymous" />
        <link rel="preload" href="/Fonts/News%20Deck/GRAND%20HALVA.otf" as="font" type="font/otf" crossOrigin="anonymous" />
        <link rel="preload" href="/Fonts/News%20Deck/carbon-modern-typeface-webfonts-2026-04-07-06-00-24-utc/fonts/CarbonText-Regular.woff2" as="font" type="font/woff2" crossOrigin="anonymous" />
        <link rel="preload" href="/Fonts/News%20Deck/medhorn-modern-sport-display-bold-slab-serif-2026-04-07-05-58-49-utc/Web-PS/Medhorn.woff2" as="font" type="font/woff2" crossOrigin="anonymous" />
        <link rel="preload" href="/Fonts/News%20Deck/eroded-personal-use/ERODED%20PERSONAL%20USE.ttf" as="font" type="font/ttf" crossOrigin="anonymous" />
        <link rel="preload" href="/Fonts/News%20Deck/vintage-typist/VintageTypist.otf" as="font" type="font/otf" crossOrigin="anonymous" />
        <link rel="preload" href="/Fonts/News%20Deck/bramos/Bramos.otf" as="font" type="font/otf" crossOrigin="anonymous" />
        <link rel="preload" href="/Fonts/News%20Deck/the-cheelaved/TheCheelaved-Regular.otf" as="font" type="font/otf" crossOrigin="anonymous" />
        <link rel="preload" href="/Fonts/News%20Deck/reality-stone-personal-use/Reality%20Stone.ttf" as="font" type="font/ttf" crossOrigin="anonymous" />
        <link rel="preload" href="/Fonts/News%20Deck/crown-heritage/CrownHeritage.otf" as="font" type="font/otf" crossOrigin="anonymous" />
      </head>
      <body>{children}</body>
    </html>
  );
}
