import { defineType, defineField } from "sanity";

// An Insights article. Most posts flow in from the loathrdotcom engine, but this
// lets the user author or edit posts by hand and pick which appear on the site.
export const post = defineType({
  name: "post",
  title: "Post",
  type: "document",
  fields: [
    defineField({
      name: "title",
      title: "Title",
      type: "string",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      options: { source: "title", maxLength: 96 },
      validation: (r) => r.required(),
    }),
    defineField({
      name: "category",
      title: "Category",
      type: "string",
      options: {
        list: ["Film & TV", "Enterprise", "News Desk", "Culture", "Branding"],
      },
    }),
    defineField({ name: "excerpt", title: "Excerpt", type: "text", rows: 2 }),
    defineField({
      name: "fromEngine",
      title: "Generated by loathrdotcom",
      type: "boolean",
      description: 'Shows the "▸ from loathrdotcom" badge. Set automatically when the engine feed lands; toggle on for hand-imported engine posts.',
      initialValue: false,
    }),
    defineField({
      name: "cover",
      title: "Cover image",
      type: "image",
      options: { hotspot: true },
    }),
    defineField({
      name: "body",
      title: "Body",
      type: "array",
      of: [{ type: "block" }],
    }),
    defineField({ name: "publishedAt", title: "Published at", type: "datetime" }),
  ],
  orderings: [
    {
      title: "Published, newest",
      name: "publishedDesc",
      by: [{ field: "publishedAt", direction: "desc" }],
    },
  ],
  preview: {
    select: { title: "title", subtitle: "category", media: "cover" },
  },
});
